// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package godid

import (
	"sync"
	"time"
)

var (
	lockentryStoreMockClose                   sync.RWMutex
	lockentryStoreMockGetRange                sync.RWMutex
	lockentryStoreMockGetRangeWithAggregation sync.RWMutex
	lockentryStoreMockPut                     sync.RWMutex
)

// Ensure, that entryStoreMock does implement entryStore.
// If this is not the case, regenerate this file with moq.
var _ entryStore = &entryStoreMock{}

// entryStoreMock is a mock implementation of entryStore.
//
//     func TestSomethingThatUsesentryStore(t *testing.T) {
//
//         // make and configure a mocked entryStore
//         mockedentryStore := &entryStoreMock{
//             CloseFunc: func() error {
// 	               panic("mock out the Close method")
//             },
//             GetRangeFunc: func(parentBucketName string, start time.Time, end time.Time) ([]entry, error) {
// 	               panic("mock out the GetRange method")
//             },
//             GetRangeWithAggregationFunc: func(parentBucketName string, start time.Time, end time.Time, agg aggregationFunction) (interface{}, error) {
// 	               panic("mock out the GetRangeWithAggregation method")
//             },
//             PutFunc: func(in1 string, in2 entry) error {
// 	               panic("mock out the Put method")
//             },
//         }
//
//         // use mockedentryStore in code that requires entryStore
//         // and then make assertions.
//
//     }
type entryStoreMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetRangeFunc mocks the GetRange method.
	GetRangeFunc func(parentBucketName string, start time.Time, end time.Time) ([]entry, error)

	// GetRangeWithAggregationFunc mocks the GetRangeWithAggregation method.
	GetRangeWithAggregationFunc func(parentBucketName string, start time.Time, end time.Time, agg aggregationFunction) (interface{}, error)

	// PutFunc mocks the Put method.
	PutFunc func(in1 string, in2 entry) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetRange holds details about calls to the GetRange method.
		GetRange []struct {
			// ParentBucketName is the parentBucketName argument value.
			ParentBucketName string
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
		}
		// GetRangeWithAggregation holds details about calls to the GetRangeWithAggregation method.
		GetRangeWithAggregation []struct {
			// ParentBucketName is the parentBucketName argument value.
			ParentBucketName string
			// Start is the start argument value.
			Start time.Time
			// End is the end argument value.
			End time.Time
			// Agg is the agg argument value.
			Agg aggregationFunction
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// In1 is the in1 argument value.
			In1 string
			// In2 is the in2 argument value.
			In2 entry
		}
	}
}

// Close calls CloseFunc.
func (mock *entryStoreMock) Close() error {
	if mock.CloseFunc == nil {
		panic("entryStoreMock.CloseFunc: method is nil but entryStore.Close was just called")
	}
	callInfo := struct {
	}{}
	lockentryStoreMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockentryStoreMockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedentryStore.CloseCalls())
func (mock *entryStoreMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	lockentryStoreMockClose.RLock()
	calls = mock.calls.Close
	lockentryStoreMockClose.RUnlock()
	return calls
}

// GetRange calls GetRangeFunc.
func (mock *entryStoreMock) GetRange(parentBucketName string, start time.Time, end time.Time) ([]entry, error) {
	if mock.GetRangeFunc == nil {
		panic("entryStoreMock.GetRangeFunc: method is nil but entryStore.GetRange was just called")
	}
	callInfo := struct {
		ParentBucketName string
		Start            time.Time
		End              time.Time
	}{
		ParentBucketName: parentBucketName,
		Start:            start,
		End:              end,
	}
	lockentryStoreMockGetRange.Lock()
	mock.calls.GetRange = append(mock.calls.GetRange, callInfo)
	lockentryStoreMockGetRange.Unlock()
	return mock.GetRangeFunc(parentBucketName, start, end)
}

// GetRangeCalls gets all the calls that were made to GetRange.
// Check the length with:
//     len(mockedentryStore.GetRangeCalls())
func (mock *entryStoreMock) GetRangeCalls() []struct {
	ParentBucketName string
	Start            time.Time
	End              time.Time
} {
	var calls []struct {
		ParentBucketName string
		Start            time.Time
		End              time.Time
	}
	lockentryStoreMockGetRange.RLock()
	calls = mock.calls.GetRange
	lockentryStoreMockGetRange.RUnlock()
	return calls
}

// GetRangeWithAggregation calls GetRangeWithAggregationFunc.
func (mock *entryStoreMock) GetRangeWithAggregation(parentBucketName string, start time.Time, end time.Time, agg aggregationFunction) (interface{}, error) {
	if mock.GetRangeWithAggregationFunc == nil {
		panic("entryStoreMock.GetRangeWithAggregationFunc: method is nil but entryStore.GetRangeWithAggregation was just called")
	}
	callInfo := struct {
		ParentBucketName string
		Start            time.Time
		End              time.Time
		Agg              aggregationFunction
	}{
		ParentBucketName: parentBucketName,
		Start:            start,
		End:              end,
		Agg:              agg,
	}
	lockentryStoreMockGetRangeWithAggregation.Lock()
	mock.calls.GetRangeWithAggregation = append(mock.calls.GetRangeWithAggregation, callInfo)
	lockentryStoreMockGetRangeWithAggregation.Unlock()
	return mock.GetRangeWithAggregationFunc(parentBucketName, start, end, agg)
}

// GetRangeWithAggregationCalls gets all the calls that were made to GetRangeWithAggregation.
// Check the length with:
//     len(mockedentryStore.GetRangeWithAggregationCalls())
func (mock *entryStoreMock) GetRangeWithAggregationCalls() []struct {
	ParentBucketName string
	Start            time.Time
	End              time.Time
	Agg              aggregationFunction
} {
	var calls []struct {
		ParentBucketName string
		Start            time.Time
		End              time.Time
		Agg              aggregationFunction
	}
	lockentryStoreMockGetRangeWithAggregation.RLock()
	calls = mock.calls.GetRangeWithAggregation
	lockentryStoreMockGetRangeWithAggregation.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *entryStoreMock) Put(in1 string, in2 entry) error {
	if mock.PutFunc == nil {
		panic("entryStoreMock.PutFunc: method is nil but entryStore.Put was just called")
	}
	callInfo := struct {
		In1 string
		In2 entry
	}{
		In1: in1,
		In2: in2,
	}
	lockentryStoreMockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	lockentryStoreMockPut.Unlock()
	return mock.PutFunc(in1, in2)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//     len(mockedentryStore.PutCalls())
func (mock *entryStoreMock) PutCalls() []struct {
	In1 string
	In2 entry
} {
	var calls []struct {
		In1 string
		In2 entry
	}
	lockentryStoreMockPut.RLock()
	calls = mock.calls.Put
	lockentryStoreMockPut.RUnlock()
	return calls
}
